### ISSUE TITLE
Problems with MultiQC when running harpy align

### ISSUE THREAD

**Issue by prmunn** [pdimens/harpy#141]
### Describe the bug

The reporting step initially failed because MultiQC wasn't in my path. I added it using "export", but then got an error saying the MultiQC option --no-version-check not recognized. Removing this option and running manually appeared to work correctly. 

### Is this the latest version of Harpy?

- [X] yes
- [ ] no

### Harpy error log

```console
Activating singularity image /local/workdir/prm88/GenomicsInnovation/haplotagging/GI24017_10477404_pheniqs_run_fly/.snakemake/singularity/9176802248d67a544a6d5b6077374e16.simg
Activating conda environment: ../../../../../../conda-envs/4cccf3eee90925b520b4b9c490f9f2cb
[Fri Oct  4 16:59:33 2024]
Error in rule samtools_report:
    jobid: 11
    input: Align/bwa/reports/data/samtools_stats/C3-flyS3-10477404-22NLWYLT3-L2_trimmed.stats, Align/bwa/reports/data/samtools_flagstat/C3-flyS3-10477404-22NLWYLT3-L2_trimmed.flagstat
    output: Align/bwa/reports/bwa.stats.html
    conda-env: /conda-envs/4cccf3eee90925b520b4b9c490f9f2cb
    shell:
        multiqc Align/bwa/reports/data/samtools_stats Align/bwa/reports/data/samtools_flagstat --no-version-check --force --quiet --no-data-dir --title "Basic Alignment Statistics" --comment "This report aggregates samtools stats and samtools flagstats results for all alignments. Samtools stats ignores alignments marked as duplicates." --filename Align/bwa/reports/bwa.stats.html 2> /dev/null
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

[Fri Oct  4 17:00:13 2024]
Finished job 9.
5 of 10 steps (50%) done
[Fri Oct  4 17:00:45 2024]
Finished job 10.
6 of 10 steps (60%) done
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2024-10-04T165039.686105.snakemake.log
WorkflowError:
At least one job did not complete successfully.
```

**Comment by pdimens** [comment]
That means that, for whatever reason, Harpy isn't installing a recent version of MultiQC. A minimum version of MultiQC [was added to the Harpy code](https://github.com/pdimens/harpy/blob/ca7444bd171c57a9148b95396dbe174f53182904/harpy/_conda.py#L33C1-L33C38) that creates the hidden runtime conda environments. I think this might be a matter of uninstall/reinstall. Make sure to remove the `.snakemake` directory from your project path.

OR

A simpler test to try first would be to just remove the container in `.snakemake` and let Harpy pull the latest one. If that doesn't do it, uninstall-reinstall.

**Comment by prmunn** [comment]
Could be that I had my previous install of harpy still active. Deactivated harpy, deleted all working directories and started over - was able to keep running past the MultiQC step that caused the problem last time.
