### ISSUE TITLE
ema-h preproc -p generating empty ema-bin-xxx files

### ISSUE THREAD

**Issue by PA-GAGNAIRE** [pdimens/harpy#2]
Hello,

Thanks for this fantastic pipeline and the detailed notes that come with it, very useful!
I went through the quality trimming and read mapping modules, the snakemake rules are executed correctly, but a problem happens when running ema-h.

I checked the ema-h commands by hand one by one out of the Harpy pipeline. I found no problem with the ema-h count -p command, which outputs a ~50Mo ema-ncnt file. The ema-count Summary generated by Harpy also looks good, e.g.:

"Sample","ReadsIgnored","BarcodeValid","BarcodeTotal","PercentValid","PercentIgnored"
"Sample_1","302610","22730346","22730346","100","1.33"

But then the ema-h preproc -p command generates a list of empty ema-bin-xxx output files.

Here is the detailed command line I ran out of Harpy:
seqfu interleave -1 /my_path_to_/Trimming/Sample_1.R1.fq.gz -2 /my_path_to_/Trimming/Sample_1.R2.fq.gz | ema-h preproc -p -n 500 -t 2 -o ./ /my_path_to_/Alignments/ema/count/Sample_1.ema-ncnt

And the output:

:: Bucketing 1 inputs into 500 files with 2 threads
:: Loading known counts file /my_path_to_/Alignments/ema/count/Sample_1.ema-ncnt ... 
:: Loading known counts ... done in 4.8 s
:: File assignment ... done in 2.0 s
:: [==================================================] 0 out of 22,730,346 (100.00%)
Writing barcodes ... done in 49.5 s

Looks like although the data contain 22,730,346 valid barcodes, none of them has been processed/written by ema-h preproc -p.

Do you have any idea what might be going on here? 
Thanks!
Pierre-Alexandre

**Comment by pdimens** [comment]
That's so odd. Running preproc by hand also produces nothing?

If so, and this is something I was a little concerned about, try building ema from scratch using the bits in the build.sh file that clone the edharry branch. See if it makes a difference when you compile it on your specific system.

Let's see if we can track this down.

**Comment by PA-GAGNAIRE** [comment]
I have tested both your ema-h binary in the misc folder and rebuilding ema from scratch after cloning the haplotag branch on EdHarry's repository, but none of them worked for the preproc step on my Linux system. 
Since I have no idea what the problem is, I'm wondering if it could be the data rather than the program. Would you be willing to send me a toy dataset of yours or alternatively test a toy dataset from my data on your system to see if the problem is in the data?

Thanks for your help 
Pierre-Alexandre

**Comment by pdimens** [comment]
Thanks for trying those steps. I'm sorry neither proved to be helpful. While I'm not done ruling out software-related issues, I do like your idea of exchanging toy data. A bit later today I can send you a link to a single sample of R1/R2 files of real haplotag data (likely downsampled for convenience). I will post a link when those are available. Please let me know how I can retrieve your toy data to test on my system(s).

**Comment by PA-GAGNAIRE** [comment]
Great, thanks for your willingness to exchange toy datasets! I will also down sample my data and send you a link to download it later today.

**Comment by PA-GAGNAIRE** [comment]
Thanks! The link works I could get your files.

I realized that your R1 reads do not contain a 16-base in-line barcode followed by a 7-base poly-A join, as prepended by the 16BaseBCGen program from SamHaplotag. In fact, I did not understand that the format required by Harpy align (and ema-h) was R1 reads containing only the insert sequence. I thought it was also necessary to have the 16-base barcode + 7 joining bases added inline to R1.

I will now make a test on my data without the 23 added bases, it should work!

**Comment by PA-GAGNAIRE** [comment]
Thanks for the input! I understand that the ema-haplotag version makes the addition of inline barcodes unnecessary. 

However, the data formatting is maybe not the only issue with my data. Here is a summary of my tests:

ema-h preproc works well with your data, but not with mine, even without adding the 23 bases inline of R1 with the 16BaseBCGen program.
The format of our files is now perfectly identical, except for the length of the reads. Your data is of standard length (2\*151bp), while mine is much shorter (2\*51bp) because we generated it as part of a test run on a Novaseq SP flowcell to validate the construction of our libraries (we will sequence them in 2*151bp mode later).

To test if the length of the reads is the cause of the problem, I trimmed the last 100 bases of your reads to make them 51bp reads like mine, and now I get an empty output with your data as well. 

So the minimum read length seems to be the issue. I will try to find out where the length of the reads causes a problem in the ema code, but I'm not sure I can do it because I don't practice C++...

**Comment by pdimens** [comment]
This is sounding very familiar. I'm pretty sure ema has a minimum read length component to it. I'm not versed in Cpp either, but I can take a look tomorrow too.

**Comment by pdimens** [comment]
@PA-GAGNAIRE The source code suggests the minimum read length is 32
https://github.com/arshajii/ema/blob/bfdcea3a24dab5aaa737c345a5efa84788cdaf1d/cpp/common.h#L62

**Comment by pdimens** [comment]
@PA-GAGNAIRE given what we've discussed so far, I've updated the docs to have a page dedicated to describing the data format. https://pdimens.github.io/harpy/dataformat/

I would appreciate your feedback on it in that hopes that I cover (effectively) what's been going on with your data.

**Comment by pdimens** [comment]
FYI, I requested collaboration rights to EMA to merge the haplotagging stuff and update the conda installation, so the next version of harpy will be 100% conda installable with a totally-legit version of EMA shipped with it

**Comment by PA-GAGNAIRE** [comment]
Thank you for exploring the ema code and for the new detailed explanations of the data format in the Harpy manual. Happy to see that there will be a conda installable version of Harpy!

In the meantime I've tested the effect of read length on ema preproc output. 
First, lowering the MIN_READ_SIZE below 32 (e.g. 20) before recompiling the program doesn't change anything, I still get a list of empty ema-bin-xxx output files when read size is 51bp.
I therefore progressively trimmed the reads you supplied with cutadapt, to produce toy datasets with paired-end reads of decreasing size from 150 to 50 bp. 
Rather than observing a pure threshold effect of read length, I found that the percentage of pre-processed reads among the total decreases progressively, reaching zero between 55 and 56 bp.
It therefore looks like the way ema preprocesses reads leads to them being eliminated more likely the shorter they are, with a significant loss of data as soon as the reads are less than 75 bp, moving towards zero reads retained at around 55 bp.
I haven't had time to look in the code where this behaviour might come from... I'll try to do this soon

**Comment by pdimens** [comment]
Interesting. Good observation. Unfortunately, the EMA devs are occupied with other tasks and aren't very responsive on their repo. Happy to report Harpy is hosted on conda now, though.

**Comment by pdimens** [comment]
FWIW, I think my team may be moving away from mapping with EMA and may generally recommend using BWA. Depending on where we land with this in the next week or so, BWA may become the default and recommended workflow.

**Comment by PA-GAGNAIRE** [comment]
Thanks for letting me know! Does this mean that EMA's advantage in using BX barcode information to improve mapping is relatively limited (considering other drawbacks)? It's true that mapping reads with bwa-mem rarely cause problems, except in the presence of structural variants. Using barcodes to inform mapping may not be necessary if Laviathan can call structural variants after running BWA.

**Comment by pdimens** [comment]
It's a stale project and as it stands, it seems more problem than solution. Leviathan calls known inversions in some internal fly data we test on, and naibr does too (for BWA alignments). The next push for harpy may just be defaulting to BWA and including naibr SV calling. The documentation would also reflect this change and highlight the pros/cons of ema

**Comment by pdimens** [comment]
@PA-GAGNAIRE may I close this?

**Comment by PA-GAGNAIRE** [comment]
Yes thanks!
