### ISSUE TITLE
Update wiki to ensure module names are consistent

### ISSUE THREAD

**Issue by gmkov** [pdimens/harpy#69]
### Description of feature

Minor issue, just thought i'd let you know.

I note that at some point in the past the module harpy snp was called harpy variants; and in the wiki there are pages which still refer to harpy variants, which is a bit confusing. e.g. https://pdimens.github.io/harpy/modules/phase/

thanks

**Comment by pdimens** [comment]
Ah thanks! I hoped I had changed it everywhere but things slip through the cracks. If/when you see inconsistencies like that or think of ways that things can be phrased/explained better, I encourage you to make an edit and submit a PR using the `Edit this page` on the bottom-left of the page 
![image](https://github.com/pdimens/harpy/assets/19176506/5a8aa645-b6da-4d2c-946c-39ffd6bce8f8)
I'll make these changes now :grin:
